import styles from "../styles/Home.module.css";
import Head from 'next/head';
import Header from "../components/Header";
import StakeDetails from "../components/StakeDetails";
import StakeForm from "../components/StakeForm";


export default function Home() {
  return (
    <div  >
      <Head>
        <title>Staking Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        <div className={styles.main}>
          <StakeDetails />
          <div className={styles.form}>
            <StakeForm />
          </div>
        </div>
      </div>
    </div>
  )
}